// <auto-generated />
using System;
using AutoVendor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoVendor.Data.Migrations
{
    [DbContext(typeof(AutoVendorDbContext))]
    [Migration("20250830173646_addedProducts")]
    partial class addedProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AutoVendor.Data.Models.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identifier of brand");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Name of the brand");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = new Guid("db21ebb2-0dcc-498b-bb53-4c4cc57e2bf8"),
                            Name = "Brembo"
                        },
                        new
                        {
                            Id = new Guid("642efe8c-c0e2-41dd-8a5e-446954535ab1"),
                            Name = "Valeo"
                        },
                        new
                        {
                            Id = new Guid("cd85b9b6-0ed2-4959-9342-5fab244d7387"),
                            Name = "ATE"
                        },
                        new
                        {
                            Id = new Guid("2164b9ec-11e0-4b16-a1db-6a0950c09dc0"),
                            Name = "Castrol"
                        },
                        new
                        {
                            Id = new Guid("ae2ce0bf-2535-4868-b91c-5287b2e18de6"),
                            Name = "Lemforder"
                        },
                        new
                        {
                            Id = new Guid("7c2a53d3-a49e-4360-ac3c-92e5256a3e76"),
                            Name = "Monroe"
                        });
                });

            modelBuilder.Entity("AutoVendor.Data.Models.BrandModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identifier of the brand model car");

                    b.Property<string>("Fuel")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasComment("Fuel type");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Image of the car");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)")
                        .HasComment("Name of the brand model car");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasComment("Year of the model");

                    b.HasKey("Id");

                    b.ToTable("BrandModels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("645e4786-5af0-4ef8-bf10-315b7bae5ec6"),
                            Fuel = "Petrol",
                            ImageUrl = "https://curvaconcepts.com/wp-content/uploads/silver-f30-bmw-340i-c300-4.jpg",
                            Name = "BMW F30 340i",
                            Year = 2016
                        },
                        new
                        {
                            Id = new Guid("f595f66d-d96b-4565-a7d8-891e0bac99b3"),
                            Fuel = "Petrol",
                            ImageUrl = "https://hips.hearstapps.com/hmg-prod/amv-prod-cad-assets/images/11q4/424156/2012-mercedes-benz-c63-amg-coupe-black-series-photo-429266-s-original.jpg",
                            Name = "Mercedes-Benz C63",
                            Year = 2012
                        },
                        new
                        {
                            Id = new Guid("b98e20d3-2638-4989-9c9d-f07813e7b772"),
                            Fuel = "Petrol",
                            ImageUrl = "https://urotuning.photos/image/lf9x07sa.jpeg",
                            Name = "BMW G30 540i",
                            Year = 2018
                        },
                        new
                        {
                            Id = new Guid("1d90ff81-6003-4f07-839f-434b58bb7819"),
                            Fuel = "Petrol",
                            ImageUrl = "https://images.hgmsites.net/hug/2015-mercedes-benz-cls-class_100552115_h.jpg",
                            Name = "Mercedes-Benz CLS 550",
                            Year = 2016
                        });
                });

            modelBuilder.Entity("AutoVendor.Data.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identifier of the category");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Image of the given category");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Name of the category");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8769df37-a0c0-4465-95dc-c7bb38ab976f"),
                            ImageUrl = "https://www.autopower.bg/images/categories/%D0%A1%D0%BF%D0%B8%D1%80%D0%B0%D1%87%D0%BD%D0%B0%20%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%B0.jpg",
                            Name = "Braking System"
                        },
                        new
                        {
                            Id = new Guid("fb2f6da8-cf97-4907-92db-f9da9ab27e3f"),
                            ImageUrl = "https://www.autopower.bg/images/categories/%D0%9E%D0%BA%D0%B0%D1%87%D0%B2%D0%B0%D0%BD%D0%B5%20%D0%BD%D0%B0%20%D0%BA%D0%BE%D0%BB%D0%B5%D0%BB%D0%B0%D1%82%D0%B0.jpg",
                            Name = "Wheel Suspension"
                        },
                        new
                        {
                            Id = new Guid("89523138-906e-4ef9-87b7-a58af8a7e5a7"),
                            ImageUrl = "https://www.autopower.bg/images/categories/%D0%9A%D0%BE%D1%80%D0%BC%D0%B8%D0%BB%D0%BD%D0%B0%20%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%B0.jpg",
                            Name = "Steering System"
                        },
                        new
                        {
                            Id = new Guid("18d611cc-5359-4233-9476-c31a881b642f"),
                            ImageUrl = "https://www.autopower.bg/images/categories/%D0%A0%D0%B5%D0%BC%D1%8A%D1%87%D0%BD%D0%BE%20%D0%B7%D0%B0%D0%B4%D0%B2%D0%B8%D0%B6%D0%B2%D0%B0%D0%BD%D0%B5.jpg",
                            Name = "Belt Drive"
                        },
                        new
                        {
                            Id = new Guid("35b9f799-d8c8-4349-84fd-3e56220185f5"),
                            ImageUrl = "https://www.autopower.bg/images/categories/%D0%9C%D0%B0%D1%81%D0%BB%D0%B0%20%D0%B8%20%D1%82%D0%B5%D1%87%D0%BD%D0%BE%D1%81%D1%82%D0%B8.jpg",
                            Name = "Oils and liquids"
                        },
                        new
                        {
                            Id = new Guid("e6370d79-3ff3-47b6-b93a-cced4774ffe4"),
                            ImageUrl = "https://www.autopower.bg/images/categories/%D0%A4%D0%B8%D0%BB%D1%82%D1%80%D0%B8.jpg",
                            Name = "Filters"
                        });
                });

            modelBuilder.Entity("AutoVendor.Data.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identifier of the product");

                    b.Property<Guid>("AppliableTo")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Can be applied to many car models");

                    b.Property<Guid>("BelongToCategory")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Category of the Product");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Description about the product");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Product image");

                    b.Property<Guid>("Manufacturer")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Manufacturer of the product");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasComment("Name of the Product");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Price of the product");

                    b.HasKey("Id");

                    b.HasIndex("AppliableTo");

                    b.HasIndex("BelongToCategory");

                    b.HasIndex("Manufacturer");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("360a30d5-846d-4be0-b813-98851ec306d2"),
                            AppliableTo = new Guid("e78aed86-427b-4fc9-b2cd-a144b78c0de4"),
                            BelongToCategory = new Guid("f6905fef-6e23-402b-9e9f-265862a45aea"),
                            Description = "The price is for 1 brake disc. For vehicles with M-performance brakes",
                            ImageUrl = "https://www.autopower.bg/images/%D1%81%D0%BF%D0%B8%D1%80%D0%B0%D1%87%D0%B5%D0%BD-%D0%B4%D0%B8%D1%81%D0%BA-BREMBO-PRIME-LINE-Composite-09C39413-BMW-3-Sedan-F30-F35-F80-340-i-xDrive-imagetabig-845520901700425-BREMBO.jpg",
                            Manufacturer = new Guid("003c6c86-80ef-4aa6-9e46-88c7ec45203e"),
                            Name = "Brake disc BREMBO PRIME LINE - Composite",
                            Price = 540m
                        },
                        new
                        {
                            Id = new Guid("75dce1d9-e57f-4fae-b042-8f79f1322fa8"),
                            AppliableTo = new Guid("8a41e64e-a37c-4e3f-89de-254f845badcc"),
                            BelongToCategory = new Guid("f6905fef-6e23-402b-9e9f-265862a45aea"),
                            Description = "The price is for 1 brake disc.",
                            ImageUrl = "https://www.autopower.bg/images/%D1%81%D0%BF%D0%B8%D1%80%D0%B0%D1%87%D0%B5%D0%BD-%D0%B4%D0%B8%D1%81%D0%BA-BREMBO-PRIME-LINE-Dual-Cast-09A94533-Mercedes-C-class-Saloon-w204-C-63-AMG-204.077-imagetabig-845520901699467-BREMBO.jpg",
                            Manufacturer = new Guid("003c6c86-80ef-4aa6-9e46-88c7ec45203e"),
                            Name = "Brake disc BREMBO PRIME LINE - Dual Cast",
                            Price = 1600m
                        });
                });

            modelBuilder.Entity("AutoVendor.Data.Models.Product", b =>
                {
                    b.HasOne("AutoVendor.Data.Models.BrandModel", "BrandModel")
                        .WithMany("Products")
                        .HasForeignKey("AppliableTo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoVendor.Data.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("BelongToCategory")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoVendor.Data.Models.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("Manufacturer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("BrandModel");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AutoVendor.Data.Models.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("AutoVendor.Data.Models.BrandModel", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("AutoVendor.Data.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
