// <auto-generated />
using System;
using AutoVendor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoVendor.Data.Migrations
{
    [DbContext(typeof(AutoVendorDbContext))]
    [Migration("20250830172413_SeedDB")]
    partial class SeedDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AutoVendor.Data.Models.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identifier of brand");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Name of the brand");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = new Guid("003c6c86-80ef-4aa6-9e46-88c7ec45203e"),
                            Name = "Brembo"
                        },
                        new
                        {
                            Id = new Guid("7a2fdf0a-cbdb-4bc0-8578-ffbe68250a3e"),
                            Name = "Valeo"
                        },
                        new
                        {
                            Id = new Guid("38a64e1c-9abf-43dc-9fdb-7e5fe7caf2d7"),
                            Name = "ATE"
                        },
                        new
                        {
                            Id = new Guid("8b5df958-dc1a-4bf6-af44-af8d9c894e43"),
                            Name = "Castrol"
                        },
                        new
                        {
                            Id = new Guid("f522beba-9c4a-401d-9ba0-009a1788c629"),
                            Name = "Lemforder"
                        },
                        new
                        {
                            Id = new Guid("17f94596-1034-4dff-9f0e-0017e6f0cfd4"),
                            Name = "Monroe"
                        });
                });

            modelBuilder.Entity("AutoVendor.Data.Models.BrandModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identifier of the brand model car");

                    b.Property<string>("Fuel")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasComment("Fuel type");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Image of the car");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)")
                        .HasComment("Name of the brand model car");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasComment("Year of the model");

                    b.HasKey("Id");

                    b.ToTable("BrandModels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e78aed86-427b-4fc9-b2cd-a144b78c0de4"),
                            Fuel = "Petrol",
                            ImageUrl = "https://curvaconcepts.com/wp-content/uploads/silver-f30-bmw-340i-c300-4.jpg",
                            Name = "BMW F30 340i",
                            Year = 2016
                        },
                        new
                        {
                            Id = new Guid("8a41e64e-a37c-4e3f-89de-254f845badcc"),
                            Fuel = "Petrol",
                            ImageUrl = "https://hips.hearstapps.com/hmg-prod/amv-prod-cad-assets/images/11q4/424156/2012-mercedes-benz-c63-amg-coupe-black-series-photo-429266-s-original.jpg",
                            Name = "Mercedes-Benz C63",
                            Year = 2012
                        },
                        new
                        {
                            Id = new Guid("d53e1ae1-d74d-4730-aa13-7bac65bbae00"),
                            Fuel = "Petrol",
                            ImageUrl = "https://urotuning.photos/image/lf9x07sa.jpeg",
                            Name = "BMW G30 540i",
                            Year = 2018
                        },
                        new
                        {
                            Id = new Guid("5730d314-db00-44ce-9679-762ba4224d0a"),
                            Fuel = "Petrol",
                            ImageUrl = "https://images.hgmsites.net/hug/2015-mercedes-benz-cls-class_100552115_h.jpg",
                            Name = "Mercedes-Benz CLS 550",
                            Year = 2016
                        });
                });

            modelBuilder.Entity("AutoVendor.Data.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identifier of the category");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Image of the given category");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Name of the category");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f6905fef-6e23-402b-9e9f-265862a45aea"),
                            ImageUrl = "https://www.autopower.bg/images/categories/%D0%A1%D0%BF%D0%B8%D1%80%D0%B0%D1%87%D0%BD%D0%B0%20%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%B0.jpg",
                            Name = "Braking System"
                        },
                        new
                        {
                            Id = new Guid("a9ec2dee-05a2-479e-a242-2fd166ee62c3"),
                            ImageUrl = "https://www.autopower.bg/images/categories/%D0%9E%D0%BA%D0%B0%D1%87%D0%B2%D0%B0%D0%BD%D0%B5%20%D0%BD%D0%B0%20%D0%BA%D0%BE%D0%BB%D0%B5%D0%BB%D0%B0%D1%82%D0%B0.jpg",
                            Name = "Wheel Suspension"
                        },
                        new
                        {
                            Id = new Guid("21f5d9a3-acb6-4ab3-b9b8-d8a81606d611"),
                            ImageUrl = "https://www.autopower.bg/images/categories/%D0%9A%D0%BE%D1%80%D0%BC%D0%B8%D0%BB%D0%BD%D0%B0%20%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%B0.jpg",
                            Name = "Steering System"
                        },
                        new
                        {
                            Id = new Guid("aafbcf17-8eef-47c7-b992-34e8007c9f90"),
                            ImageUrl = "https://www.autopower.bg/images/categories/%D0%A0%D0%B5%D0%BC%D1%8A%D1%87%D0%BD%D0%BE%20%D0%B7%D0%B0%D0%B4%D0%B2%D0%B8%D0%B6%D0%B2%D0%B0%D0%BD%D0%B5.jpg",
                            Name = "Belt Drive"
                        },
                        new
                        {
                            Id = new Guid("90e98b71-8bd8-4847-abf5-26ffc22cdd52"),
                            ImageUrl = "https://www.autopower.bg/images/categories/%D0%9C%D0%B0%D1%81%D0%BB%D0%B0%20%D0%B8%20%D1%82%D0%B5%D1%87%D0%BD%D0%BE%D1%81%D1%82%D0%B8.jpg",
                            Name = "Oils and liquids"
                        },
                        new
                        {
                            Id = new Guid("c9efcea4-ceae-4128-9533-2efa52ade047"),
                            ImageUrl = "https://www.autopower.bg/images/categories/%D0%A4%D0%B8%D0%BB%D1%82%D1%80%D0%B8.jpg",
                            Name = "Filters"
                        });
                });

            modelBuilder.Entity("AutoVendor.Data.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identifier of the product");

                    b.Property<Guid>("AppliableTo")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Can be applied to many car models");

                    b.Property<Guid>("BelongToCategory")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Category of the Product");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Description about the product");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Product image");

                    b.Property<Guid>("Manufacturer")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Manufacturer of the product");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasComment("Name of the Product");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Price of the product");

                    b.HasKey("Id");

                    b.HasIndex("AppliableTo");

                    b.HasIndex("BelongToCategory");

                    b.HasIndex("Manufacturer");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("AutoVendor.Data.Models.Product", b =>
                {
                    b.HasOne("AutoVendor.Data.Models.BrandModel", "BrandModel")
                        .WithMany("Products")
                        .HasForeignKey("AppliableTo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoVendor.Data.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("BelongToCategory")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoVendor.Data.Models.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("Manufacturer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("BrandModel");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AutoVendor.Data.Models.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("AutoVendor.Data.Models.BrandModel", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("AutoVendor.Data.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
